CREATE TABLE REPORT
(
   CARGO_ID         SERIAL PRIMARY KEY NOT NULL,
   PRF_HME_RESIDUE  BOOLEAN,
   PRF_HME_WASHING  BOOLEAN,
   CREATED_AT       TIMESTAMP NOT NULL,
   UPDATED_AT       TIMESTAMP NOT NULL
);

CREATE TABLE REF
(
  PORT_ID       SERIAL PRIMARY KEY NOT NULL,
  VALUE         INTEGER UNIQUE NOT NULL,
  CREATED_AT    TIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP NOT NULL,
  REPORT_ID     INTEGER REFERENCES REPORT(REPORT_ID),
);

CREATE TABLE PORT
(
  PORT_ID       SERIAL PRIMARY KEY NOT NULL,
  NAME          VARCHAR(200) UNIQUE NOT NULL,
  REGION        VARCHAR(200),
  CREATED_AT    TIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP NOT NULL,
  REPORT_ID     INTEGER REFERENCES REPORT(REPORT_ID),
);

CREATE TABLE CARGO
(
  CARGO_ID      SERIAL PRIMARY KEY NOT NULL,
  NAME          VARCHAR(200) UNIQUE NOT NULL,
  REGION        VARCHAR(200),
  CREATED_AT    TIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP NOT NULL,
  REPORT_ID     INTEGER REFERENCES REPORT(REPORT_ID)
);

CREATE TABLE BERTH
(
  BERTH_ID      SERIAL PRIMARY KEY NOT NULL,
  BERTH         VARCHAR(200) UNIQUE NOT NULL,
  CREATED_AT    TIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP NOT NULL,
  REPORT_ID     INTEGER REFERENCES REPORT(REPORT_ID),
);

CREATE TABLE REPORTED_PROBLEMS
(
  CARGO_ID      SERIAL PRIMARY KEY NOT NULL,
  PROBLEMS      TEXT,
  CREATED_AT    TIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP NOT NULL,
  REPORT_ID     INTEGER REFERENCES REPORT(REPORT_ID),
);